MetaDataFormat = "toml"
publishdir = "../temp_larsth.github.io"
baseurl = "http://www.larsth.dk/"
languageCode = "da-DK"
title = "Lars Tørnes Hansen | Blog"

canonifyurls = true

#
#theme = "hyde-x"
theme = "vienna"
paginate = 10
# Copyright notice. This is displayer in the footer.
copyright = "Copyright &copy; 2015 Lars Tørnes Hansen"

[author]
    name = "Lars Tørnes Hansen"

[permalinks]
    post = "/:year/:month/:day/:filename/"

[indexes]
    category = "kategorier"

#
# All parameters below here are optional and can be mixed and matched.
# (BEGIN: vienna theme params)
[params]
    # Used when a given page doesn't set its own.
    subtitle = "Blog om IT, Teknik og Naturvidenskab"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Metadata used to drive integrations.
    #googleAuthorship = "Your Google+ profile ID"
    googleAuthorship = "110410393931214784146"
    #googleAnalytics = "Your Google Analytics tracking code"
    #gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "larsth"
    #bitbucket = ""
    #linkedin = ""
    googleplus = "https://plus.google.com/110410393931214784146/posts"
    #facebook = ""
    twitter = "LarsTHansen"
    
    # (END: vienna theme params)
